### ISSUE TITLE
:bug: witness compose non serial joint

### ISSUE THREAD

**Issue by qiangshou007** [smart-dag/sdag#1]
![image](https://user-images.githubusercontent.com/39160078/54599602-ed0a1200-4a75-11e9-9cce-0ae58b15bcdd.png)

**Comment by qiangshou007** [comment]
red 'w2' can not see former 'w2' may be as former can not be free joints right now, need to analysis

**Comment by Xudong-Huang** [comment]
we should use wide search to find the latest self unstable joint, the original algorithm was deep search which may miss the latest one, also we should ignore those that marked as no-good self unstable joint
