### ISSUE TITLE
new algorithm for non-serial detection

### ISSUE THREAD

**Issue by Xudong-Huang** [smart-dag/sdag#13]
we only save one good unstable unit for each address in a hashmap. if there is no unstable joint for the address, just remove the entry.

any new coming unit if include the previous good self unstable unit, then just replace it with the new coming one, and mark the coming one as good.

if the new coming unit's address is not in the hashmap, just insert it and mark as good.

otherwise, mark the new coming address as non-serial bad.

this way we could save a lot of graph search, and speedy the non-serial detection.

**Comment by qiangshou007** [comment]
new algorithm will improve compose logic, example get last my unstable joint.
